class TcaNla:
    """Netlink attribute name constants for TC filter validation.

    These mirror the nla_map string entries defined in pyroute2's
    tcmsg classes (cls_flower, cls_matchall, common_act, __init__).
    """

    # --- tcmsg top-level ---
    KIND = 'TCA_KIND'
    OPTIONS = 'TCA_OPTIONS'
    CHAIN = 'TCA_CHAIN'

    # --- flower options ---
    FLOWER_ACT = 'TCA_FLOWER_ACT'
    FLOWER_KEY_ETH_TYPE = 'TCA_FLOWER_KEY_ETH_TYPE'
    FLOWER_KEY_IP_PROTO = 'TCA_FLOWER_KEY_IP_PROTO'
    FLOWER_KEY_IPV4_SRC = 'TCA_FLOWER_KEY_IPV4_SRC'
    FLOWER_KEY_IPV4_SRC_MASK = 'TCA_FLOWER_KEY_IPV4_SRC_MASK'
    FLOWER_KEY_IPV4_DST = 'TCA_FLOWER_KEY_IPV4_DST'
    FLOWER_KEY_IPV4_DST_MASK = 'TCA_FLOWER_KEY_IPV4_DST_MASK'
    FLOWER_KEY_IPV6_SRC = 'TCA_FLOWER_KEY_IPV6_SRC'
    FLOWER_KEY_IPV6_SRC_MASK = 'TCA_FLOWER_KEY_IPV6_SRC_MASK'
    FLOWER_KEY_IPV6_DST = 'TCA_FLOWER_KEY_IPV6_DST'
    FLOWER_KEY_IPV6_DST_MASK = 'TCA_FLOWER_KEY_IPV6_DST_MASK'
    FLOWER_KEY_TCP_DST = 'TCA_FLOWER_KEY_TCP_DST'
    FLOWER_KEY_UDP_DST = 'TCA_FLOWER_KEY_UDP_DST'
    FLOWER_KEY_ENC_KEY_ID = 'TCA_FLOWER_KEY_ENC_KEY_ID'
    FLOWER_KEY_ENC_IPV4_SRC = 'TCA_FLOWER_KEY_ENC_IPV4_SRC'
    FLOWER_KEY_ENC_IPV4_DST = 'TCA_FLOWER_KEY_ENC_IPV4_DST'
    FLOWER_KEY_ENC_UDP_DST_PORT = 'TCA_FLOWER_KEY_ENC_UDP_DST_PORT'
    FLOWER_KEY_ENC_OPTS = 'TCA_FLOWER_KEY_ENC_OPTS'
    FLOWER_KEY_FLAGS = 'TCA_FLOWER_KEY_FLAGS'
    FLOWER_KEY_FLAGS_MASK = 'TCA_FLOWER_KEY_FLAGS_MASK'
    FLOWER_KEY_PORT_DST_MIN = 'TCA_FLOWER_KEY_PORT_DST_MIN'
    FLOWER_KEY_PORT_DST_MAX = 'TCA_FLOWER_KEY_PORT_DST_MAX'

    # --- matchall options ---
    MATCHALL_ACT = 'TCA_MATCHALL_ACT'

    # --- action ---
    ACT_KIND = 'TCA_ACT_KIND'
